version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://demo:demo@db:5432/demo
      - JWT_SECRET=change_this_to_a_secure_value
      - REFRESH_TOKEN_SECRET=change_this_to_a_secure_value
      - AES_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      - NODE_ENV=development
    ports:
      - "4000:3001"
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app

volumes:
  db-data:
